name: Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and clone repository
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm t
